### ISSUE TITLE
PerfTracker processing

### ISSUE THREAD

**Issue by knupel** [alexr4/datamoshing-GLSL#1]
Hi Alex, I try to find a way to download PerfTracker processing but the server don't respond,
there is a link to download it?
By the way can you give me an authorization to use your datamoshing in my [shader framework](https://github.com/StanLepunK/Shader)? that's a very nice effect to add in Romanesco !

**Comment by alexr4** [comment]
Hi Stan,

I've totally forgot to link the perftracker. It's a custom library for monitoring performance.
I haven't release it yet, you can delete it from the project. I will release it with my shader library in few days/weeks

Of course you can use it on your shader frameworks ;)

**Comment by knupel** [comment]
I'm interested by your performance library keep in touch if you publish it, that's can be nice tool !

thanks !

**Comment by alexr4** [comment]
Sure I will.
Basically, it's inspired by the stats.js library. It's perform framerate , millis, memory and custom tracking on a sample of frames. You may have seen it on my Instagram post lately.

Like my shader based filters library, we are on testing phase at the studio and working on a release in the next few weeks or days
😉
